<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\protocol\SteamHidBridge.Protocol\SteamHidBridge.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="appsettings.example.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
